In [101]:
import pandas as pd
df=pd.read_csv('data.csv')


In [102]:
selected_features = [
    "concave points_worst", "perimeter_worst", "concave points_mean",
    "radius_worst", "perimeter_mean", "area_worst",
    "radius_mean", "area_mean", "concavity_mean", "concavity_worst"
]

In [103]:
X = df[selected_features]  # Independent variables
Y = df["diagnosis"]  # Target variable 

In [104]:
X,Y

(     concave points_worst  perimeter_worst  concave points_mean  radius_worst  \
 0                  0.2654           184.60              0.14710        25.380   
 1                  0.1860           158.80              0.07017        24.990   
 2                  0.2430           152.50              0.12790        23.570   
 3                  0.2575            98.87              0.10520        14.910   
 4                  0.1625           152.20              0.10430        22.540   
 ..                    ...              ...                  ...           ...   
 564                0.2216           166.10              0.13890        25.450   
 565                0.1628           155.00              0.09791        23.690   
 566                0.1418           126.70              0.05302        18.980   
 567                0.2650           184.60              0.15200        25.740   
 568                0.0000            59.16              0.00000         9.456   
 
      perimete

In [105]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y) 

In [106]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [107]:

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [108]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) 

In [109]:
X_train

array([[ 0.9320124 , -1.24792009, -0.11914956, ..., -1.1391179 ,
         2.82313451,  4.67282796],
       [ 2.6989469 ,  2.08161691,  2.66503199, ...,  1.85197292,
         2.01311199,  1.92862053],
       [-0.97023893, -1.24522047, -0.69650228, ..., -1.10978518,
        -0.36555756, -0.64491059],
       ...,
       [-1.23903365, -0.37984081, -1.10551525, ..., -0.06142266,
        -1.02856666, -1.12796759],
       [ 1.05001236,  0.20387802,  0.43005885, ..., -0.15477966,
         0.29858532,  0.63253231],
       [-0.61102866, -0.67559968, -0.80434493, ..., -0.5518995 ,
        -0.81969927, -0.76538799]])

In [110]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Models for evaluation
models = {
    "Linear Regression": LinearRegression(),  # Linear Regression as a classifier
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier()
}

# Threshold for binary classification (you can adjust this threshold based on your problem)
threshold = 0.5

# Evaluate models
results = {}
for name, model in models.items():
    model.fit(X_train, Y_train)  # Train model
    y_pred = model.predict(X_test)  # Predict continuous values with Linear Regression

    # For Linear Regression, convert continuous predictions to binary (0 or 1)
    if name == "Linear Regression":
        y_pred_binary = (y_pred > threshold).astype(int)  # Convert to binary class based on threshold
    else:
        y_pred_binary = y_pred  # For classifiers, y_pred is already binary

    # Store the evaluation metrics
    results[name] = {
        "Accuracy": accuracy_score(Y_test, y_pred_binary),
        "Precision": precision_score(Y_test, y_pred_binary),
        "Recall": recall_score(Y_test, y_pred_binary),
        "F1-score": f1_score(Y_test, y_pred_binary),
    }

# Print results
for model, metrics in results.items():
    print(f"\nModel: {model}")
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")



Model: Linear Regression
Accuracy: 0.9561
Precision: 0.9750
Recall: 0.9070
F1-score: 0.9398

Model: Random Forest
Accuracy: 0.9474
Precision: 0.9512
Recall: 0.9070
F1-score: 0.9286

Model: Decision Tree
Accuracy: 0.9211
Precision: 0.9250
Recall: 0.8605
F1-score: 0.8916


In [111]:
X_train, Y_train

(array([[ 0.9320124 , -1.24792009, -0.11914956, ..., -1.1391179 ,
          2.82313451,  4.67282796],
        [ 2.6989469 ,  2.08161691,  2.66503199, ...,  1.85197292,
          2.01311199,  1.92862053],
        [-0.97023893, -1.24522047, -0.69650228, ..., -1.10978518,
         -0.36555756, -0.64491059],
        ...,
        [-1.23903365, -0.37984081, -1.10551525, ..., -0.06142266,
         -1.02856666, -1.12796759],
        [ 1.05001236,  0.20387802,  0.43005885, ..., -0.15477966,
          0.29858532,  0.63253231],
        [-0.61102866, -0.67559968, -0.80434493, ..., -0.5518995 ,
         -0.81969927, -0.76538799]]),
 array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
   

In [112]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# Models for evaluation
models = {
    "Linear Regression (Binarized)": LinearRegression(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier()
}

# Evaluate models
results = {}
for name, model in models.items():
    model.fit(X_train, Y_train)  # Train the model
    
    if name == "Linear Regression (Binarized)":
        y_pred_prob = model.predict(X_test)  # Continuous prediction
        y_pred = np.where(y_pred_prob >= 0.5, 1, 0)  # Binarize predictions
    else:
        y_pred = model.predict(X_test)  # For classifiers, use direct predictions
    
    # Store evaluation metrics
    results[name] = {
        "Accuracy": accuracy_score(Y_test, y_pred),
        "Precision": precision_score(Y_test, y_pred),
        "Recall": recall_score(Y_test, y_pred),
        "F1-score": f1_score(Y_test, y_pred),
    }

# Print results
for model, metrics in results.items():
    print(f"\nModel: {model}")
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")



Model: Linear Regression (Binarized)
Accuracy: 0.9561
Precision: 0.9750
Recall: 0.9070
F1-score: 0.9398

Model: Random Forest
Accuracy: 0.9561
Precision: 0.9524
Recall: 0.9302
F1-score: 0.9412

Model: Decision Tree
Accuracy: 0.9386
Precision: 0.9500
Recall: 0.8837
F1-score: 0.9157


In [113]:
results

{'Linear Regression (Binarized)': {'Accuracy': 0.956140350877193,
  'Precision': 0.975,
  'Recall': 0.9069767441860465,
  'F1-score': 0.9397590361445783},
 'Random Forest': {'Accuracy': 0.956140350877193,
  'Precision': 0.9523809523809523,
  'Recall': 0.9302325581395349,
  'F1-score': 0.9411764705882353},
 'Decision Tree': {'Accuracy': 0.9385964912280702,
  'Precision': 0.95,
  'Recall': 0.8837209302325582,
  'F1-score': 0.9156626506024096}}

In [114]:
sorted_results = dict(sorted(results.items(), key=lambda item: item[1]["Accuracy"], reverse=True))


In [115]:
sorted_results

{'Linear Regression (Binarized)': {'Accuracy': 0.956140350877193,
  'Precision': 0.975,
  'Recall': 0.9069767441860465,
  'F1-score': 0.9397590361445783},
 'Random Forest': {'Accuracy': 0.956140350877193,
  'Precision': 0.9523809523809523,
  'Recall': 0.9302325581395349,
  'F1-score': 0.9411764705882353},
 'Decision Tree': {'Accuracy': 0.9385964912280702,
  'Precision': 0.95,
  'Recall': 0.8837209302325582,
  'F1-score': 0.9156626506024096}}